# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fillials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=256, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('fillial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fillials.Fillials')),
            ],
            options={
                'verbose_name': 'Профиль мастера',
                'verbose_name_plural': 'Профили мастеров',
            },
        ),
        migrations.CreateModel(
            name='MasterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Тип мастера',
                'verbose_name_plural': 'Типы мастеров',
            },
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='master_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.MasterType'),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
