# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillials', '0002_remove_fillials_slug'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='fillial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fillials.Fillials'),
            preserve_default=False,
        ),
    ]
