# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_masterservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprofile',
            name='master_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.MasterType'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.MasterProfile'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fillials.FillialServices'),
        ),
    ]
