# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170502_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterservice',
            name='profile',
        ),
        migrations.AddField(
            model_name='masterservice',
            name='profile',
            field=models.ManyToManyField(default=None, null=True, to='profiles.MasterProfile'),
        ),
    ]
