# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170425_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='fillial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fillials.Fillials'),
        ),
    ]
