# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170426_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprofile',
            name='fillial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fillials.Fillials'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='master_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.MasterType'),
        ),
    ]
