# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fillials', '0007_auto_20170418_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('fillial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillials.Fillials')),
            ],
        ),
    ]
