# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
