# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fillials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='fillals/avatars')),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Филлиал',
                'verbose_name_plural': 'Филлиалы',
            },
        ),
        migrations.CreateModel(
            name='FillialServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('fillal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillials.Fillials')),
                ('service_title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.Services')),
            ],
            options={
                'verbose_name': 'Услуга филлиала',
                'verbose_name_plural': 'Услуги филлиала',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='fillials/gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fillial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillials.Fillials')),
            ],
            options={
                'verbose_name': 'Картинка для галереи',
                'verbose_name_plural': 'Картинки для галереи',
            },
        ),
    ]
