# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillials',
            name='slug',
        ),
    ]
