# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillials', '0004_fillials_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillialServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='fillal',
        ),
        migrations.AlterModelOptions(
            name='fillials',
            options={'verbose_name': 'Филлиал', 'verbose_name_plural': 'Филлиалы'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Картинка для галереи', 'verbose_name_plural': 'Картинки для галереи'},
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='fillialservices',
            name='fillal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillials.Fillials'),
        ),
    ]
