# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('fillials', '0005_auto_20170418_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillialservices',
            name='service_title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.Services'),
        ),
    ]
