# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillials', '0006_fillialservices_service_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillialservices',
            options={'verbose_name': 'Услуга филлиала', 'verbose_name_plural': 'Услуги филлиала'},
        ),
    ]
